---
title: "Animal activity analysis"
author: "Francisco E. Fonturbel and Javier Cuadra"
date: "26/jun/2019"
output: 
  html_document:
    includes:
        after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 01 - Introduction

**Animal activity** is a central issue on ecology, as it determines the outcome of ecological interactions, influeces community structure and also explains many auto-ecological processes. Ecological studies on animal activity rely on information sources such as telemetry (VHF, GPS or NFC among others) or camera traps. In the recent years, camera traps have been widely used in wildlife ecology studies as they provide high-quality data (if properly used, of course) with minimum observer interference, and are a cost-effective method to monitor large areas with little time investment.

Processing activity data, however, can be bothersome and even frustrating without a prior knowledge about how to deal with this kind of data. By definition, activity data is circular (i.e., measured in time o angular units) and therefore cannot be analyzed using standard statistical procedures such as `anova` or `glm` that assume linear data. For example, in circular data the time difference between 1:15 and 1:45 h is the same than 23:55 and 0:25 h, but if we operate these differences as linear data the results would be quite different. In circular data the beginning and the end points are the same and thus we need a special framework to analyze these patterns.

Here we present a short guide on animal activity analysis based on [R](https://cran.r-project.org/) plus [RStudio](https://www.rstudio.com/) open source platform. The whole tutorial is hosted on our lab repository at [GitHub](https://github.com/fonturbel-lab) and it will be continously updated by our lab members and collaborators.

### Contents

We start our 'self-service' tutorial with **Circular statistics** to analyze activity patterns around the clock. Then, we go with the **Activity kernels** that are a graphic approach to characterize activity functions. And once we mastered kernel functions, we can assess **Overlap** between two activity kernels and formally test hypotheses about them.

## References